version: "3.9"

services:
  app:
    env_file:
      - .env.local
    build: .
    ports:
      - "8888:80"
    volumes:
      - ./app:/rails/app
      - ./config:/rails/config
      - ./models:/rails/models
      - ./public:/rails/public
      - ./storage:/rails/storage
